(package
  (name packrat)
  (version 0.1)
  (license "MIT")
  (authors "Peter Lane, LShift Ltd. <query at lshift dot net> ,Tony Garnock-Jones <tonyg at kcbbs dot gen dot nz>")
  (maintainers "Arthur Maciel <arthurmaciel at gmail dot com>")
  (description "Packrat Parser Library")
  (tags "language extensions")
  (docs "https://github.com/cyclone-scheme/cyclone-winds/wiki/packrat")
  (test "test.scm")
  (dependencies ())
  (test-dependencies ())
  (foreign-dependencies ())
  (library
    (name (cyclone packrat))
    (description "Packrat Parser Library")))
